config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :movies
  resources :theaters
  resources :show_times

  resources :users, only: [:create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :show_times
    validates :name, presence: true
end

app/models/show_time.rb
class ShowTime < ApplicationRecord
    belongs_to :movie
    belongs_to :theater
end

app/models/theater.rb
class Theater < ApplicationRecord
    has_many :show_times
    validates :name, :city_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save :downcase_name
    validates :name, :password, presence: true
    validates :name, uniqueness: true

    def downcase_name
        self.name = name.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.create(movies_params)
        if @movie.save
            redirect_to movies_path
        else
            render "new"
        end
    end

    def edit
        movie
    end

    def update
        movie.update(movies_params)
        if @movie.save
            redirect_to movies_path
        else
            render "edit"
        end
    end

    def destroy
    end

    private

    def movies_params
        params.require(:movie).permit(:name, :genre, :format, :a_u)
    end

    def movie
        @movie = Movie.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(name: params[:session][:name].downcase)
        if user.present?
            session[:user_id] = user.id
            redirect_to root_path
        else
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

end

app/controllers/show_times_controller.rb
class ShowTimesController < ApplicationController
    def index
        @show_times = ShowTime.all
    end

    def show
    end

    def new
        @show_time = ShowTime.new
    end

    def create
        @show_time = ShowTime.create(show_times_params)
        if @show_time.save
            redirect_to show_times_path
        else
            render "new"
        end
    end

    def edit
        show_time
    end

    def update
        show_time.update(show_times_params)
        if show_time.save
            redirect_to show_times_path
        else
            render "edit"
        end
    end

    def destroy
    end

    private

    def show_times_params
        params.require(:show_time).permit(:movie_id, :date, :timing, :theater_id)
    end

    def show_time
        @show_time = ShowTime.find(params[:id])
    end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
    def index
        @theaters = Theater.all
    end

    def show
        theater
        @show_times = theater.show_times
    end

    def new
        @theater = Theater.new
    end

    def create
        @theater = Theater.create(theaters_params)
        if @theater.save
            redirect_to theaters_path
        else
            render "new"
        end
    end

    def edit
        theater
    end

    def update
        theater.update(theaters_params)
        if @theater.save
            redirect_to theaters_path
        else
            render "edit"
        end
    end

    def destroy
    end

    def theaters_params
        params.require(:theater).permit(:name, :city_name, :seats)
    end

    def theater
        @theater = Theater.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            redirect_to root_path
        else
            render "new"
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        User.find(session[:user_id]) if session[:user_id] != nil
    end

    def is_admin?
        current_user.admin
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_times_helper.rb
module ShowTimesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>

<% if current_user.present? %>
    <%= "Welcome #{current_user.name}" =%>
    <br/>
    <%= link_to "Logout", logout_path =%> <br/>

<% else %>
    <p> Welcome User</p>
    <br/>
    <%= link_to "Sign Up", signup_path =%> 
    <%= link_to "Login", login_path =%> 
<% end %>

<%= link_to "Movies", movies_path =%>
<%= link_to "Theater", theaters_path =%> 
<%= link_to "ShoW-times", show_times_path =%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MachineTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= f.label :name =%>
<%= f.text_field :name =%>
<br/>
<%= f.label "a/u" =%>
<%= f.text_field :a_u =%>
<br/>
<%= f.label :genre =%>
<%= f.text_field :genre =%>
<br/>
<%= f.label :format =%>
<%= f.text_field :format =%>
<br/>

app/views/movies/edit.html.erb
<p>Edit Movie</p>
<%= form_for @movie, method: :patch do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/movies/index.html.erb
<%= link_to "<Back", root_path =%>
<% if current_user.present? && is_admin? %>
    <%= link_to "Add Movies", new_movie_path =%>
<% end %>
<h3>Movies (<%= @movies.count =%>)</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>  
            <th>Name</th>
            <th>Genre</th>
            <th>Format</th>
        </tr>
    </thead>
    <tbody>
        <% @movies.each do |movie| %>
            <tr>
                <td><%= movie.id =%></td>  
                <td><%= movie.name =%></td> 
                <td><%= movie.genre=%></td> 
                <td><%= movie.format=%></td> 
                <% if current_user.present? && is_admin? %>
                    <td>
                        <%= link_to "edit", edit_movie_path(movie) =%>
                    </td> 
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/movies/new.html.erb
<p>create new Movie</p>
<%= form_for @movie, method: :post do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
    <%= obj.errors.full_messages.each do |error| =%>
        <%= error =%>
    <% end %>
<% end %>

app/views/show_times/_form.html.erb
<%= f.label :date =%>
<%= f.date_field :date =%>
<br/>
<%= f.label :timing =%>
<%= f.time_field :timing =%>
<br/>
<%= f.label :theater_id =%>
<%= f.collection_select :theater_id, Theater.all, :id, :name =%>
<br/>
<%= f.label :movie_id =%>
<%= f.collection_select :movie_id, Movie.all, :id, :name =%>
<br/>

app/views/show_times/edit.html.erb
<p>Edit ShowTime</p>
<%= form_for @show_time, method: :patch do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/show_times/index.html.erb
<%= link_to "<Back", root_path =%>
<% if current_user.present? && is_admin? %>
    <%= link_to "Add Show-Times", new_show_time_path =%>
<% end %>
<h3>ShowTimes(<%= @show_times.count =%>)</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>  
            <th>Theater Name</th>
            <th>Movie Name</th>
            <th>Date</th>
            <th>Timing</th>
            
        </tr>
    </thead>
    <tbody>
        <% @show_times.each do |st| %>
            <tr>
                <td><%= st.id =%></td>  
                <td><%= st.theater.name =%></td> 
                <td><%= st.movie.name =%></td> 
                <td><%= st.date =%></td>
                <td><%= st.timing =%></td>
                <% if current_user.present? && is_admin? %>
                    <td>
                        <%= link_to "edit", edit_show_time_path(st) =%>
                    </td> 
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/show_times/new.html.erb
<p>create new ShowTime</p>
<%= form_for @show_time, method: :post do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/theaters/_form.html.erb
<%= f.label :name =%>
<%= f.text_field :name =%>
<br/>
<%= f.label :city_name =%>
<%= f.text_field :city_name =%>
<br/>
<%= f.label :seats =%>
<%= f.text_field :seats =%>
<br/>

app/views/theaters/edit.html.erb
<p>Edit Theater</p>
<%= form_for @theater, method: :patch do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/theaters/index.html.erb
<%= link_to "<Back", root_path =%>
<% if current_user.present? && is_admin? %>
    <%= link_to "Add Theater", new_theater_path =%>
<% end %>

<h3>Theater (<%= @theaters.count =%>)</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>  
            <th>Name</th>
            <th>City Name</th>
            <th>AVL Seats</th>
        </tr>
    </thead>
    <tbody>
        <% @theaters.each do |theater| %>
            <tr>
                <td><%= link_to theater.id, theater =%></td>  
                <td><%= theater.name =%></td> 
                <td><%= theater.city_name=%></td> 
                <td><%= theater.seats=%></td> 
                <% if current_user.present? && is_admin? %>
                    <td>
                        <%= link_to "edit", edit_theater_path(theater) =%>
                    </td> 
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/theaters/new.html.erb
<p>create new Theater</p>
<%= form_for @theater, method: :post do |f| =%>
    <%= render "form", f: f =%>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", :back =%>
    </button>
<% end %>

app/views/theaters/show.html.erb
<%= link_to "<Back", theaters_path =%>
<div>
    <h4>Theater Details :</h4>
    <p>Name : <span><%= @theater.name =%></span></p>
    <p>City Name: <span><%= @theater.city_name =%></span></p>
    <p>Seats : <span><%= @theater.seats =%></span></p>
</div>

<div>
    <h4>Show times details: </h4>
    <p>upcoming shows(<%= @show_times.count =%>)</p>
    <table class="table">
    <thead>
        <tr>
            <th>Id</th>  
            <th>Movie Name</th>
            <th>Date</th>
            <th>Timing</th>
        </tr>
    </thead>
    <tbody>
        <% @show_times.each do |st| %>
            <tr>
                <td><%= st.id =%></td>  
                <td><%= st.movie.name =%></td> 
                <td><%= st.date =%></td>
                <td><%= st.timing =%></td>
            </tr>
        <% end %>
    </tbody>
</table>

</div>

app/views/users/new.html.erb
<p>create new user</p>
<%= render 'shared/errors', obj: @user =%>
<%= form_for @user, method: :post do |f| =%>
    <%= f.label :name =%>
    <%= f.text_field :name =%>
    <br/>
    <%= f.label :password =%>
    <%= f.password_field :password =%>
    <br/>
    <%= f.submit =%>
    <button>
        <%= link_to "cancel", root_path =%>
    </button>
<% end %>